# Generated by Django 5.1.2 on 2026-01-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FilePathField(max_length=500)),
                ('total_lines', models.IntegerField()),
                ('total_certificados', models.IntegerField()),
                ('total_alunos', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
