# Generated by Django 5.2.10 on 2026-01-27 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('script_path', models.CharField(max_length=500, unique=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_stdout', models.TextField(blank=True, null=True)),
                ('last_stderr', models.TextField(blank=True, null=True)),
                ('last_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
